version: '3.3'
services:
    web:
        image: php:7.3-apache
        build:
            context: ./webapp
            dockerfile: Dockerfile
        container_name: php_container
        restart: always
        depends_on:
            - db
        volumes:
            - ./webapp:/var/www/html/ 
        ports:
            - 8080:80
    db:
        container_name: mysql_container
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: MyDatabase
            MYSQL_USER: timmy186
            MYSQL_PASSWORD: mypass123
        ports:
            - 3306:3306